parameters:
- name: image_type
  displayName: Build Agent Image
  type: string
  default: windows2019
  values:
  - windows2019
  - windows2022
  - ubuntu2004
  - ubuntu2204
- name: variable_group
  displayName: Variable Group
  type: string
  default: BuildAgents
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: CI Windows2019
- name: depends_on
  displayName: First Job Depends On
  type: object
  default: ' '
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .

jobs:
- job: createvmimageversion
  displayName: Create New Gallery VMImage Version (${{ parameters.image_type }})
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 90
  pool: 
    name: ${{ parameters.agent_pool }}
  variables:
  - name: ImageType
    value: ${{ parameters.image_type }}
  - name: ManagedImageId
    value: $[stageDependencies.convert_template_to_managedvm.managedimagegeneration.outputs['createmanagedimage.ManagedImageId'] ]
  - group: ${{ parameters.variable_group }}

  steps:
  - checkout: self
  - ${{ if ne(parameters.repository_base_path, '.') }}:
    - checkout: ${{ parameters.repository_base_path }}
  - task: PowerShell@2
    displayName: 'Create new Gallery Virtual Machine Image version'
    inputs:
      targetType: filePath
      filePath: ${{ parameters.repository_base_path }}/scripts/create-gallery-vmimageversion.ps1
      arguments: -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -ResourceGroup $(AZURE_AGENTS_RESOURCE_GROUP) `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -TenantId $(AZURE_TENANT) `
                 -Location $(AZURE_LOCATION) `
                 -GalleryName $(GALLERY_NAME) `
                 -GalleryResourceGroup $(GALLERY_RESOURCE_GROUP) `
                 -ImageType $(ImageType) `
                 -ManagedImageId $(ManagedImageId)