parameters:
- name: variable_group_name
  displayName: Variable Group
  type: string
  default: 'Image Generation Variables'
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: CI Windows2019
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .
- name: build_stage_job_name
  displayName: Name of the stage and job that builds the image
  type: string
  default: buildagent_template_vm

jobs:
- job: createvmimageversion
  displayName: Create New Gallery VMImage Version
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 90
  pool:
    name: ${{ parameters.agent_pool }}
    
  variables:
  - name: GalleryVmImageDefinition
    value: $[stageDependencies.${{parameters.build_stage_job_name}}.generate_image.outputs['setVars.GalleryVmImageDefinition'] ]
  - name: ManagedImageName
    value: $[stageDependencies.${{parameters.build_stage_job_name}}.generate_image.outputs['setVars.ManagedImageNameOutput'] ]
  - name: GalleryStorageAccountType
    value: $[stageDependencies.${{parameters.build_stage_job_name}}.generate_image.outputs['setVars.GalleryStorageAccountType'] ]
  - group: ${{ parameters.variable_group_name }}

  steps:
  - checkout: self
  - ${{ if ne(parameters.repository_base_path, '.') }}:
    - checkout: ${{ parameters.repository_base_path }}
  - task: PowerShell@2
    displayName: 'Create new Gallery Virtual Machine Image version'
    name: creategalleryimageversion
    inputs:
      targetType: filePath
      filePath: ${{ parameters.repository_base_path }}/scripts/create-gallery-vmimageversion.ps1
      arguments: -ManagedImageName $(ManagedImageName) `
                 -BuildId $(Build.BuildId) `
                 -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -ResourceGroup $(AZURE_RESOURCE_GROUP) `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -TenantId $(AZURE_TENANT) `
                 -Location $(AZURE_LOCATION) `
                 -GalleryName $(GALLERY_NAME) `
                 -GalleryResourceGroup $(GALLERY_RESOURCE_GROUP) `
                 -GalleryStorageAccountType $(GalleryStorageAccountType) `
                 -GalleryVmImageDefinition $(GalleryVmImageDefinition) 
