parameters:
- name: image_type
  displayName: Build Agent Image
  type: string
  default: ubuntu2204
  values:
  - windows2019
  - windows2022
  - ubuntu2004
  - ubuntu2204
- name: variable_group
  displayName: Variable Group
  type: string
  default: BuildAgents
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: 'Host Pool - Image'

trigger: none

variables:
  - group: ${{ parameters.variable_group }}

stages:
  - stage: buildagent_template_vm
    displayName: 'Build Agent Template VM'
    jobs: 
    - template: buildagent-generation-template.yml
      parameters: 
        image_type: ${{ parameters.image_type }}
        variable_group: ${{ parameters.variable_group }}
        agent_pool: ${{ parameters.agent_pool }}

  - stage: convert_template_to_managedvm
    displayName: 'Convert Template to Managed Build Agent VM'
    dependsOn: buildagent_template_vm
    jobs:
    - template: buildagent-generation-managedvm.yml
      parameters: 
        image_type: ${{ parameters.image_type }}
        variable_group: ${{ parameters.variable_group }}
        agent_pool: ${{ parameters.agent_pool }}

  - stage: create_gallery_imagevm
    displayName:  'Create Gallery Image Version VM'
    dependsOn: convert_template_to_managedvm
    jobs:
    - template: buildagent-generation-galleryvm.yml
      parameters: 
        image_type: ${{ parameters.image_type }}
        variable_group: ${{ parameters.variable_group }}
        agent_pool: ${{ parameters.agent_pool }}

