parameters:
- name: variable_group_name
  displayName: Variable Group
  type: string
  default: 'BuildAgents'
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: 'Host Pool - Image'
- name: delete_type
  displayName: 'Delete vmss (VM Scale Set) or galleryvm (Gallery VM) image?'
  type: string
  default: galleryvm
  values:
  - galleryvm
  - vmss
- name: gallery_images_to_keep
  displayName: Number of image versions to keep in gallery
  type: number
  default: 3
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .

stages:
- stage: delete_gallery_imagevm
  displayName:  'Delete Gallery Image Version VM'
  condition: eq('${{ parameters.delete_type }}', 'galleryvm')
  jobs:
  - template: managedimage-cleanup-galleryvm.yml
    parameters: 
      variable_group_name: ${{ parameters.variable_group_name }}
      agent_pool: ${{ parameters.agent_pool }}
      repository_base_path: ${{ parameters.repository_base_path }}
      gallery_images_to_keep: ${{ parameters.gallery_images_to_keep }}

- stage: delete_vmss_imagevm
  displayName:  'Delete orphaned Managed Images'
  condition: eq('${{ parameters.delete_type }}', 'vmss')
  jobs:
  - template: managedimage-cleanup-managedvm.yml
    parameters: 
      variable_group_name: ${{ parameters.variable_group_name }}
      agent_pool: ${{ parameters.agent_pool }}
      repository_base_path: ${{ parameters.repository_base_path }}
