parameters:
- name: variable_group
  displayName: Variable Group
  type: string
  default: BuildAgents
- name: gallery_threshold
  displayName: Number of image versions to keep in gallery
  type: integer
  default: 3
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: 'Host Pool - Image'
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .

jobs:
- job: cleanupobsoletevmrunnerimages
  displayName: 'Cleanup obsolete VM Gallery runner images'
  pool: 
    name: ${{ parameters.agent_pool }}
  variables:
  - group: ${{ parameters.variable_group }}

  steps:
  - checkout: self
  - ${{ if ne(parameters.repository_base_path, '.') }}:
    - checkout: ${{ parameters.repository_base_path }}
  - task: PowerShell@2
    displayName: 'Remove obsolete VM Gallery runner Images'
    inputs:
      targetType: filePath
      filePath: ${{ parameters.repository_base_path }}/scripts/cleanup-gallery-vmimageversion.ps1
      arguments: -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -TenantId $(AZURE_TENANT) `
                 -ResourceGroup $(AZURE_AGENTS_RESOURCE_GROUP) `
                 -GalleryName $(GALLERY_NAME) `
                 -GalleryResourceGroup $(GALLERY_RESOURCE_GROUP) `
                 -ImageCountThreshold ${{ parameters.gallery_threshold }}
